# Generated by Django 6.0 on 2025-12-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
            preserve_default=False,
        ),
    ]
